version: '3.4'

networks:
   frontend:
   backend:


services:
  catalog:
    image: events1/eventcatalogapi1
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseServer: mssqlserver
      DatabaseName: EventCatalogDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!) 
      ExternalCatalogUrl: http://localhost:7006
    ports: 
      - "7006:80"
    container_name: eventscatalogapi1
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: events1/webmvc
    build:
      context: .\WebMVC
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EventUrl: http://catalog
      IdentityUrl: http://192.168.1.23:7660
      CallBackUrl: http://localhost:7600
    ports:
      - "7600:80"
    container_name: eventWebshop
    networks:
      - frontend
    depends_on: 
      - catalog
      - tokenserver

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:7600
    ports:
      - "7660:80"
    container_name: eventstokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1456:1433"
    container_name: eventssqlserver
    networks: 
      - backend

